apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-deployment
rules:
  - apiGroups: ["*"]
    resources:
      - deployments
      - pods
    verbs:
      - list
      - get
      - watch
      - create
      - patch
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-deployment
roleRef:
  kind: Role
  name: api-deployment
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector: 
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec: 
      containers:
      - name: angular
        image: dhartl231198/k3s-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5200
        resources:
          limits:
            cpu: "2000m"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "50Mi"
---
kind: Service
apiVersion: v1
metadata:
 name: api-service
spec:
 selector:
   app: api
 ports:
 - protocol: TCP
   port: 5200
   nodePort: 30081
 type: NodePort
