apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-api
rules:
  - apiGroups: ["*"]
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-api
roleRef:
  kind: Role
  name: k8s-api
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api
spec:
  selector: 
    matchLabels:
      app: k8s-api
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-api
    spec: 
      containers:
      - name: k8s-api
        image: dhartl231198/k8s-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5200
        resources:
          limits:
            cpu: "2000m"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "50Mi"
---
kind: Service
apiVersion: v1
metadata:
 name: k8s-api
spec:
 selector:
   app: k8s-api
 ports:
 - protocol: TCP
   port: 5200
   nodePort: 30081
 type: NodePort
